# Generated by Django 3.0.5 on 2020-04-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200422_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image.png', upload_to='users'),
        ),
    ]
