# Generated by Django 3.0.5 on 2020-04-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_image_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image.png', upload_to='media/users'),
        ),
    ]
